package cmd

import (
	"fmt"
)

var argumentRenames = map[string]string{
	"ec2.create-image.no-no-reboot":                      "reboot",
	"ec2.*.no-egress":                                    "ingress",
	"ec2.*.no-disable-api-termination":                   "enable-api-termination",
	"elastictranscoder.*.output":                         "job-output",
	"swf.register-activity-type.version":                 "activity-version",
	"swf.register-workflow-type.version":                 "workflow-version",
	"datapipeline.*.query":                               "objects-query",
	"datapipeline.get-pipeline-definition.version":       "pipeline-version",
	"emr.*.job-flow-ids":                                 "cluster-ids",
	"emr.*.job-flow-id":                                  "cluster-id",
	"cloudsearchdomain.search.query":                     "search-query",
	"cloudsearchdomain.suggest.query":                    "suggest-query",
	"sns.subscribe.endpoint":                             "notification-endpoint",
	"deploy.*.s-3-location":                              "s3-location",
	"deploy.*.ec-2-tag-filters":                          "ec2-tag-filters",
	"codepipeline.get-pipeline.version":                  "pipeline-version",
	"codepipeline.create-custom-action-type.version":     "action-version",
	"codepipeline.delete-custom-action-type.version":     "action-version",
	"kinesisanalytics.add-application-output.output":     "application-output",
	"kinesisanalyticsv2.add-application-output.output":   "application-output",
	"route53.delete-traffic-policy.version":              "traffic-policy-version",
	"route53.get-traffic-policy.version":                 "traffic-policy-version",
	"route53.update-traffic-policy-comment.version":      "traffic-policy-version",
	"gamelift.create-build.version":                      "build-version",
	"gamelift.update-build.version":                      "build-version",
	"gamelift.create-script.version":                     "script-version",
	"gamelift.update-script.version":                     "script-version",
	"route53domains.view-billing.start":                  "start-time",
	"route53domains.view-billing.end":                    "end-time",
	"apigateway.create-rest-api.version":                 "api-version",
	"apigatewayv2.create-api.version":                    "api-version",
	"apigatewayv2.update-api.version":                    "api-version",
	"pinpoint.get-campaign-version.version":              "campaign-version",
	"pinpoint.get-segment-version.version":               "segment-version",
	"pinpoint.delete-email-template.version":             "template-version",
	"pinpoint.delete-in-app-template.version":            "template-version",
	"pinpoint.delete-push-template.version":              "template-version",
	"pinpoint.delete-sms-template.version":               "template-version",
	"pinpoint.delete-voice-template.version":             "template-version",
	"pinpoint.get-email-template.version":                "template-version",
	"pinpoint.get-in-app-template.version":               "template-version",
	"pinpoint.get-push-template.version":                 "template-version",
	"pinpoint.get-sms-template.version":                  "template-version",
	"pinpoint.get-voice-template.version":                "template-version",
	"pinpoint.update-email-template.version":             "template-version",
	"pinpoint.update-in-app-template.version":            "template-version",
	"pinpoint.update-push-template.version":              "template-version",
	"pinpoint.update-sms-template.version":               "template-version",
	"pinpoint.update-voice-template.version":             "template-version",
	"stepfunctions.send-task-success.output":             "task-output",
	"clouddirectory.publish-schema.version":              "schema-version",
	"mturk.list-qualification-types.query":               "types-query",
	"workdocs.create-notification-subscription.endpoint": "notification-endpoint",
	"workdocs.describe-users.query":                      "user-query",
	"lex-models.delete-bot.version":                      "bot-version",
	"lex-models.delete-intent.version":                   "intent-version",
	"lex-models.delete-slot-type.version":                "slot-type-version",
	"lex-models.get-intent.version":                      "intent-version",
	"lex-models.get-slot-type.version":                   "slot-type-version",
	"lex-models.delete-bot-version.version":              "bot-version",
	"lex-models.delete-intent-version.version":           "intent-version",
	"lex-models.delete-slot-type-version.version":        "slot-type-version",
	"lex-models.get-export.version":                      "resource-version",
	"license-manager.get-grant.version":                  "grant-version",
	"license-manager.delete-grant.version":               "grant-version",
	"license-manager.get-license.version":                "license-version",
	"rekognition.create-stream-processor.output":         "stream-processor-output",
	"eks.create-cluster.version":                         "kubernetes-version",
	"eks.update-cluster-version.version":                 "kubernetes-version",
	"eks.create-nodegroup.version":                       "kubernetes-version",
	"eks.update-nodegroup-version.version":               "kubernetes-version",
	"schemas.*.version":                                  "schema-version",
	"sagemaker.delete-image-version.version":             "version-number",
	"sagemaker.describe-image-version.version":           "version-number",
	"sagemaker.list-aliases.version":                     "version-number",
	"sagemaker.update-image-version.version":             "version-number",
	"iotwireless.*.lo-ra-wan":                            "lorawan",
	"codepipeline.get-action-type.version":               "action-version",
	"ecs.*.no-enable-execute-command":                    "disable-execute-command",
	"ecs.execute-command.no-interactive":                 "non-interactive",
	"controltower.create-landing-zone.version":           "landing-zone-version",
	"controltower.update-landing-zone.version":           "landing-zone-version",
	"glue.get-unfiltered-partition-metadata.region":      "resource-region",
	"glue.get-unfiltered-partitions-metadata.region":     "resource-region",
	"glue.get-unfiltered-table-metadata.region":          "resource-region",
}

func renameFlag(service, operation, flag string) string {
	for pattern, name := range argumentRenames {
		if pattern == fmt.Sprintf("%s.%s.%s", service, operation, flag) ||
			pattern == fmt.Sprintf("%s.*.%s", service, flag) {
			return name
		}
	}
	return flag
}
