package botocore

func init() {
	services = map[string]string{
		"accessanalyzer":                      "Access Analyzer",
		"account":                             "AWS Account",
		"acm-pca":                             "AWS Certificate Manager Private Certificate Authority",
		"acm":                                 "AWS Certificate Manager",
		"aiops":                               "AWS AI Ops",
		"amp":                                 "Amazon Prometheus Service",
		"amplify":                             "AWS Amplify",
		"amplifybackend":                      "AmplifyBackend",
		"amplifyuibuilder":                    "AWS Amplify UI Builder",
		"apigateway":                          "Amazon API Gateway",
		"apigatewaymanagementapi":             "AmazonApiGatewayManagementApi",
		"apigatewayv2":                        "AmazonApiGatewayV2",
		"appconfig":                           "Amazon AppConfig",
		"appconfigdata":                       "AWS AppConfig Data",
		"appfabric":                           "AppFabric",
		"appflow":                             "Amazon Appflow",
		"appintegrations":                     "Amazon AppIntegrations Service",
		"application-autoscaling":             "Application Auto Scaling",
		"application-insights":                "Amazon CloudWatch Application Insights",
		"application-signals":                 "Amazon CloudWatch Application Signals",
		"applicationcostprofiler":             "AWS Application Cost Profiler",
		"appmesh":                             "AWS App Mesh",
		"apprunner":                           "AWS App Runner",
		"appstream":                           "Amazon AppStream",
		"appsync":                             "AWS AppSync",
		"arc-region-switch":                   "ARC - Region switch",
		"arc-zonal-shift":                     "AWS ARC - Zonal Shift",
		"artifact":                            "AWS Artifact",
		"athena":                              "Amazon Athena",
		"auditmanager":                        "AWS Audit Manager",
		"autoscaling-plans":                   "AWS Auto Scaling Plans",
		"autoscaling":                         "Auto Scaling",
		"b2bi":                                "AWS B2B Data Interchange",
		"backup-gateway":                      "AWS Backup Gateway",
		"backup":                              "AWS Backup",
		"backupsearch":                        "AWS Backup Search",
		"batch":                               "AWS Batch",
		"bcm-dashboards":                      "AWS Billing and Cost Management Dashboards",
		"bcm-data-exports":                    "AWS Billing and Cost Management Data Exports",
		"bcm-pricing-calculator":              "AWS Billing and Cost Management Pricing Calculator",
		"bcm-recommended-actions":             "AWS Billing and Cost Management Recommended Actions",
		"bedrock-agent-runtime":               "Agents for Amazon Bedrock Runtime",
		"bedrock-agent":                       "Agents for Amazon Bedrock",
		"bedrock-agentcore-control":           "Amazon Bedrock AgentCore Control",
		"bedrock-agentcore":                   "Amazon Bedrock AgentCore",
		"bedrock-data-automation-runtime":     "Runtime for Amazon Bedrock Data Automation",
		"bedrock-data-automation":             "Data Automation for Amazon Bedrock",
		"bedrock-runtime":                     "Amazon Bedrock Runtime",
		"bedrock":                             "Amazon Bedrock",
		"billing":                             "AWS Billing",
		"billingconductor":                    "AWSBillingConductor",
		"braket":                              "Braket",
		"budgets":                             "AWS Budgets",
		"ce":                                  "AWS Cost Explorer Service",
		"chatbot":                             "AWS Chatbot",
		"chime-sdk-identity":                  "Amazon Chime SDK Identity",
		"chime-sdk-media-pipelines":           "Amazon Chime SDK Media Pipelines",
		"chime-sdk-meetings":                  "Amazon Chime SDK Meetings",
		"chime-sdk-messaging":                 "Amazon Chime SDK Messaging",
		"chime-sdk-voice":                     "Amazon Chime SDK Voice",
		"chime":                               "Amazon Chime",
		"cleanrooms":                          "AWS Clean Rooms Service",
		"cleanroomsml":                        "AWS Clean Rooms ML",
		"cloud9":                              "AWS Cloud9",
		"cloudcontrol":                        "AWS Cloud Control API",
		"clouddirectory":                      "Amazon CloudDirectory",
		"cloudformation":                      "AWS CloudFormation",
		"cloudfront-keyvaluestore":            "Amazon CloudFront KeyValueStore",
		"cloudfront":                          "Amazon CloudFront",
		"cloudhsm":                            "Amazon CloudHSM",
		"cloudhsmv2":                          "AWS CloudHSM V2",
		"cloudsearch":                         "Amazon CloudSearch",
		"cloudsearchdomain":                   "Amazon CloudSearch Domain",
		"cloudtrail-data":                     "AWS CloudTrail Data Service",
		"cloudtrail":                          "AWS CloudTrail",
		"cloudwatch":                          "Amazon CloudWatch",
		"codeartifact":                        "CodeArtifact",
		"codebuild":                           "AWS CodeBuild",
		"codecatalyst":                        "Amazon CodeCatalyst",
		"codecommit":                          "AWS CodeCommit",
		"codeconnections":                     "AWS CodeConnections",
		"codeguru-reviewer":                   "Amazon CodeGuru Reviewer",
		"codeguru-security":                   "Amazon CodeGuru Security",
		"codeguruprofiler":                    "Amazon CodeGuru Profiler",
		"codepipeline":                        "AWS CodePipeline",
		"codestar-connections":                "AWS CodeStar connections",
		"codestar-notifications":              "AWS CodeStar Notifications",
		"cognito-identity":                    "Amazon Cognito Identity",
		"cognito-idp":                         "Amazon Cognito Identity Provider",
		"cognito-sync":                        "Amazon Cognito Sync",
		"comprehend":                          "Amazon Comprehend",
		"comprehendmedical":                   "AWS Comprehend Medical",
		"compute-optimizer-automation":        "Compute Optimizer Automation",
		"compute-optimizer":                   "AWS Compute Optimizer",
		"configservice":                       "AWS Config",
		"connect-contact-lens":                "Amazon Connect Contact Lens",
		"connect":                             "Amazon Connect Service",
		"connectcampaigns":                    "AmazonConnectCampaignService",
		"connectcampaignsv2":                  "AmazonConnectCampaignServiceV2",
		"connectcases":                        "Amazon Connect Cases",
		"connectparticipant":                  "Amazon Connect Participant Service",
		"controlcatalog":                      "AWS Control Catalog",
		"controltower":                        "AWS Control Tower",
		"cost-optimization-hub":               "Cost Optimization Hub",
		"cur":                                 "AWS Cost and Usage Report Service",
		"customer-profiles":                   "Amazon Connect Customer Profiles",
		"databrew":                            "AWS Glue DataBrew",
		"dataexchange":                        "AWS Data Exchange",
		"datapipeline":                        "AWS Data Pipeline",
		"datasync":                            "AWS DataSync",
		"datazone":                            "Amazon DataZone",
		"dax":                                 "Amazon DynamoDB Accelerator (DAX)",
		"deadline":                            "AWSDeadlineCloud",
		"deploy":                              "AWS CodeDeploy",
		"detective":                           "Amazon Detective",
		"devicefarm":                          "AWS Device Farm",
		"devops-guru":                         "Amazon DevOps Guru",
		"directconnect":                       "AWS Direct Connect",
		"discovery":                           "AWS Application Discovery Service",
		"dlm":                                 "Amazon Data Lifecycle Manager",
		"dms":                                 "AWS Database Migration Service",
		"docdb-elastic":                       "Amazon DocumentDB Elastic Clusters",
		"docdb":                               "Amazon DocumentDB with MongoDB compatibility",
		"drs":                                 "Elastic Disaster Recovery Service",
		"ds-data":                             "AWS Directory Service Data",
		"ds":                                  "AWS Directory Service",
		"dsql":                                "Amazon Aurora DSQL",
		"dynamodb":                            "Amazon DynamoDB",
		"dynamodbstreams":                     "Amazon DynamoDB Streams",
		"ebs":                                 "Amazon Elastic Block Store",
		"ec2-instance-connect":                "AWS EC2 Instance Connect",
		"ec2":                                 "Amazon Elastic Compute Cloud",
		"ecr-public":                          "Amazon Elastic Container Registry Public",
		"ecr":                                 "Amazon Elastic Container Registry",
		"ecs":                                 "Amazon EC2 Container Service",
		"efs":                                 "Amazon Elastic File System",
		"eks-auth":                            "Amazon EKS Auth",
		"eks":                                 "Amazon Elastic Kubernetes Service",
		"elasticache":                         "Amazon ElastiCache",
		"elasticbeanstalk":                    "AWS Elastic Beanstalk",
		"elastictranscoder":                   "Amazon Elastic Transcoder",
		"elb":                                 "Elastic Load Balancing",
		"elbv2":                               "Elastic Load Balancing",
		"emr-containers":                      "Amazon EMR Containers",
		"emr-serverless":                      "EMR Serverless",
		"emr":                                 "Amazon EMR",
		"entityresolution":                    "AWS EntityResolution",
		"es":                                  "Amazon Elasticsearch Service",
		"events":                              "Amazon EventBridge",
		"evidently":                           "Amazon CloudWatch Evidently",
		"evs":                                 "Amazon Elastic VMware Service",
		"finspace-data":                       "FinSpace Public API",
		"finspace":                            "FinSpace User Environment Management service",
		"firehose":                            "Amazon Kinesis Firehose",
		"fis":                                 "AWS Fault Injection Simulator",
		"fms":                                 "Firewall Management Service",
		"forecast":                            "Amazon Forecast Service",
		"forecastquery":                       "Amazon Forecast Query Service",
		"frauddetector":                       "Amazon Fraud Detector",
		"freetier":                            "AWS Free Tier",
		"fsx":                                 "Amazon FSx",
		"gamelift":                            "Amazon GameLift",
		"gameliftstreams":                     "Amazon GameLift Streams",
		"geo-maps":                            "Amazon Location Service Maps V2",
		"geo-places":                          "Amazon Location Service Places V2",
		"geo-routes":                          "Amazon Location Service Routes V2",
		"glacier":                             "Amazon Glacier",
		"globalaccelerator":                   "AWS Global Accelerator",
		"glue":                                "AWS Glue",
		"grafana":                             "Amazon Managed Grafana",
		"greengrass":                          "AWS Greengrass",
		"greengrassv2":                        "AWS IoT Greengrass V2",
		"groundstation":                       "AWS Ground Station",
		"guardduty":                           "Amazon GuardDuty",
		"health":                              "AWS Health APIs and Notifications",
		"healthlake":                          "Amazon HealthLake",
		"iam":                                 "AWS Identity and Access Management",
		"identitystore":                       "AWS SSO Identity Store",
		"imagebuilder":                        "EC2 Image Builder",
		"importexport":                        "AWS Import/Export",
		"inspector-scan":                      "Inspector Scan",
		"inspector":                           "Amazon Inspector",
		"inspector2":                          "Inspector2",
		"internetmonitor":                     "Amazon CloudWatch Internet Monitor",
		"invoicing":                           "AWS Invoicing",
		"iot-data":                            "AWS IoT Data Plane",
		"iot-jobs-data":                       "AWS IoT Jobs Data Plane",
		"iot-managed-integrations":            "Managed integrations for AWS IoT Device Management",
		"iot":                                 "AWS IoT",
		"iotanalytics":                        "AWS IoT Analytics",
		"iotdeviceadvisor":                    "AWS IoT Core Device Advisor",
		"iotevents-data":                      "AWS IoT Events Data",
		"iotevents":                           "AWS IoT Events",
		"iotfleetwise":                        "AWS IoT FleetWise",
		"iotsecuretunneling":                  "AWS IoT Secure Tunneling",
		"iotsitewise":                         "AWS IoT SiteWise",
		"iotthingsgraph":                      "AWS IoT Things Graph",
		"iottwinmaker":                        "AWS IoT TwinMaker",
		"iotwireless":                         "AWS IoT Wireless",
		"ivs-realtime":                        "Amazon Interactive Video Service RealTime",
		"ivs":                                 "Amazon Interactive Video Service",
		"ivschat":                             "Amazon Interactive Video Service Chat",
		"kafka":                               "Managed Streaming for Kafka",
		"kafkaconnect":                        "Managed Streaming for Kafka Connect",
		"kendra-ranking":                      "Amazon Kendra Intelligent Ranking",
		"kendra":                              "AWSKendraFrontendService",
		"keyspaces":                           "Amazon Keyspaces",
		"keyspacesstreams":                    "Amazon Keyspaces Streams",
		"kinesis-video-archived-media":        "Amazon Kinesis Video Streams Archived Media",
		"kinesis-video-media":                 "Amazon Kinesis Video Streams Media",
		"kinesis-video-signaling":             "Amazon Kinesis Video Signaling Channels",
		"kinesis-video-webrtc-storage":        "Amazon Kinesis Video WebRTC Storage",
		"kinesis":                             "Amazon Kinesis",
		"kinesisanalytics":                    "Amazon Kinesis Analytics",
		"kinesisanalyticsv2":                  "Amazon Kinesis Analytics",
		"kinesisvideo":                        "Amazon Kinesis Video Streams",
		"kms":                                 "AWS Key Management Service",
		"lakeformation":                       "AWS Lake Formation",
		"lambda":                              "AWS Lambda",
		"launch-wizard":                       "AWS Launch Wizard",
		"lex-models":                          "Amazon Lex Model Building Service",
		"lex-runtime":                         "Amazon Lex Runtime Service",
		"lexv2-models":                        "Amazon Lex Model Building V2",
		"lexv2-runtime":                       "Amazon Lex Runtime V2",
		"license-manager-linux-subscriptions": "AWS License Manager Linux Subscriptions",
		"license-manager-user-subscriptions":  "AWS License Manager User Subscriptions",
		"license-manager":                     "AWS License Manager",
		"lightsail":                           "Amazon Lightsail",
		"location":                            "Amazon Location Service",
		"logs":                                "Amazon CloudWatch Logs",
		"lookoutequipment":                    "Amazon Lookout for Equipment",
		"m2":                                  "AWSMainframeModernization",
		"machinelearning":                     "Amazon Machine Learning",
		"macie2":                              "Amazon Macie 2",
		"mailmanager":                         "MailManager",
		"managedblockchain-query":             "Amazon Managed Blockchain Query",
		"managedblockchain":                   "Amazon Managed Blockchain",
		"marketplace-agreement":               "AWS Marketplace Agreement Service",
		"marketplace-catalog":                 "AWS Marketplace Catalog Service",
		"marketplace-deployment":              "AWS Marketplace Deployment Service",
		"marketplace-entitlement":             "AWS Marketplace Entitlement Service",
		"marketplace-reporting":               "AWS Marketplace Reporting Service",
		"marketplacecommerceanalytics":        "AWS Marketplace Commerce Analytics",
		"mediaconnect":                        "AWS MediaConnect",
		"mediaconvert":                        "AWS Elemental MediaConvert",
		"medialive":                           "AWS Elemental MediaLive",
		"mediapackage-vod":                    "AWS Elemental MediaPackage VOD",
		"mediapackage":                        "AWS Elemental MediaPackage",
		"mediapackagev2":                      "AWS Elemental MediaPackage v2",
		"mediastore-data":                     "AWS Elemental MediaStore Data Plane",
		"mediastore":                          "AWS Elemental MediaStore",
		"mediatailor":                         "AWS MediaTailor",
		"medical-imaging":                     "AWS Health Imaging",
		"memorydb":                            "Amazon MemoryDB",
		"meteringmarketplace":                 "AWSMarketplace Metering",
		"mgh":                                 "AWS Migration Hub",
		"mgn":                                 "Application Migration Service",
		"migration-hub-refactor-spaces":       "AWS Migration Hub Refactor Spaces",
		"migrationhub-config":                 "AWS Migration Hub Config",
		"migrationhuborchestrator":            "AWS Migration Hub Orchestrator",
		"migrationhubstrategy":                "Migration Hub Strategy Recommendations",
		"mpa":                                 "AWS Multi-party Approval",
		"mq":                                  "AmazonMQ",
		"mturk":                               "Amazon Mechanical Turk",
		"mwaa-serverless":                     "AmazonMWAAServerless",
		"mwaa":                                "AmazonMWAA",
		"neptune-graph":                       "Amazon Neptune Graph",
		"neptune":                             "Amazon Neptune",
		"neptunedata":                         "Amazon NeptuneData",
		"network-firewall":                    "AWS Network Firewall",
		"networkflowmonitor":                  "Network Flow Monitor",
		"networkmanager":                      "AWS Network Manager",
		"networkmonitor":                      "Amazon CloudWatch Network Monitor",
		"notifications":                       "AWS User Notifications",
		"notificationscontacts":               "AWS User Notifications Contacts",
		"oam":                                 "CloudWatch Observability Access Manager",
		"observabilityadmin":                  "CloudWatch Observability Admin Service",
		"odb":                                 "odb",
		"omics":                               "Amazon Omics",
		"opensearch":                          "Amazon OpenSearch Service",
		"opensearchserverless":                "OpenSearch Service Serverless",
		"organizations":                       "AWS Organizations",
		"osis":                                "Amazon OpenSearch Ingestion",
		"outposts":                            "AWS Outposts",
		"panorama":                            "AWS Panorama",
		"partnercentral-channel":              "Partner Central Channel API",
		"partnercentral-selling":              "Partner Central Selling API",
		"payment-cryptography-data":           "Payment Cryptography Data Plane",
		"payment-cryptography":                "Payment Cryptography Control Plane",
		"pca-connector-ad":                    "PcaConnectorAd",
		"pca-connector-scep":                  "Private CA Connector for SCEP",
		"pcs":                                 "AWS Parallel Computing Service",
		"personalize-events":                  "Amazon Personalize Events",
		"personalize-runtime":                 "Amazon Personalize Runtime",
		"personalize":                         "Amazon Personalize",
		"pi":                                  "AWS Performance Insights",
		"pinpoint-email":                      "Amazon Pinpoint Email Service",
		"pinpoint-sms-voice-v2":               "Amazon Pinpoint SMS Voice V2",
		"pinpoint-sms-voice":                  "Amazon Pinpoint SMS and Voice Service",
		"pinpoint":                            "Amazon Pinpoint",
		"pipes":                               "Amazon EventBridge Pipes",
		"polly":                               "Amazon Polly",
		"pricing":                             "AWS Price List Service",
		"proton":                              "AWS Proton",
		"qapps":                               "QApps",
		"qbusiness":                           "QBusiness",
		"qconnect":                            "Amazon Q Connect",
		"quicksight":                          "Amazon QuickSight",
		"ram":                                 "AWS Resource Access Manager",
		"rbin":                                "Amazon Recycle Bin",
		"rds-data":                            "AWS RDS DataService",
		"rds":                                 "Amazon Relational Database Service",
		"redshift-data":                       "Redshift Data API Service",
		"redshift-serverless":                 "Redshift Serverless",
		"redshift":                            "Amazon Redshift",
		"rekognition":                         "Amazon Rekognition",
		"repostspace":                         "AWS re:Post Private",
		"resiliencehub":                       "AWS Resilience Hub",
		"resource-explorer-2":                 "AWS Resource Explorer",
		"resource-groups":                     "AWS Resource Groups",
		"resourcegroupstaggingapi":            "AWS Resource Groups Tagging API",
		"rolesanywhere":                       "IAM Roles Anywhere",
		"route53-recovery-cluster":            "Route53 Recovery Cluster",
		"route53-recovery-control-config":     "AWS Route53 Recovery Control Config",
		"route53-recovery-readiness":          "AWS Route53 Recovery Readiness",
		"route53":                             "Amazon Route 53",
		"route53domains":                      "Amazon Route 53 Domains",
		"route53profiles":                     "Route 53 Profiles",
		"route53resolver":                     "Amazon Route 53 Resolver",
		"rtbfabric":                           "RTBFabric",
		"rum":                                 "CloudWatch RUM",
		"s3api":                               "Amazon Simple Storage Service",
		"s3control":                           "AWS S3 Control",
		"s3outposts":                          "Amazon S3 on Outposts",
		"s3tables":                            "Amazon S3 Tables",
		"s3vectors":                           "Amazon S3 Vectors",
		"sagemaker-a2i-runtime":               "Amazon Augmented AI Runtime",
		"sagemaker-edge":                      "Amazon Sagemaker Edge Manager",
		"sagemaker-featurestore-runtime":      "Amazon SageMaker Feature Store Runtime",
		"sagemaker-geospatial":                "Amazon SageMaker geospatial capabilities",
		"sagemaker-metrics":                   "Amazon SageMaker Metrics Service",
		"sagemaker-runtime":                   "Amazon SageMaker Runtime",
		"sagemaker":                           "Amazon SageMaker Service",
		"savingsplans":                        "AWS Savings Plans",
		"scheduler":                           "Amazon EventBridge Scheduler",
		"schemas":                             "Schemas",
		"sdb":                                 "Amazon SimpleDB",
		"secretsmanager":                      "AWS Secrets Manager",
		"security-ir":                         "Security Incident Response",
		"securityhub":                         "AWS SecurityHub",
		"securitylake":                        "Amazon Security Lake",
		"serverlessrepo":                      "AWSServerlessApplicationRepository",
		"service-quotas":                      "Service Quotas",
		"servicecatalog-appregistry":          "AWS Service Catalog App Registry",
		"servicecatalog":                      "AWS Service Catalog",
		"servicediscovery":                    "AWS Cloud Map",
		"ses":                                 "Amazon Simple Email Service",
		"sesv2":                               "Amazon Simple Email Service",
		"shield":                              "AWS Shield",
		"signer":                              "AWS Signer",
		"signin":                              "AWS Sign-In Service",
		"simspaceweaver":                      "AWS SimSpace Weaver",
		"snow-device-management":              "AWS Snow Device Management",
		"snowball":                            "Amazon Import/Export Snowball",
		"sns":                                 "Amazon Simple Notification Service",
		"socialmessaging":                     "AWS End User Messaging Social",
		"sqs":                                 "Amazon Simple Queue Service",
		"ssm-contacts":                        "AWS Systems Manager Incident Manager Contacts",
		"ssm-guiconnect":                      "AWS SSM-GUIConnect",
		"ssm-incidents":                       "AWS Systems Manager Incident Manager",
		"ssm-quicksetup":                      "AWS Systems Manager QuickSetup",
		"ssm-sap":                             "AWS Systems Manager for SAP",
		"ssm":                                 "Amazon Simple Systems Manager (SSM)",
		"sso-admin":                           "AWS Single Sign-On Admin",
		"sso-oidc":                            "AWS SSO OIDC",
		"sso":                                 "AWS Single Sign-On",
		"stepfunctions":                       "AWS Step Functions",
		"storagegateway":                      "AWS Storage Gateway",
		"sts":                                 "AWS Security Token Service",
		"supplychain":                         "AWS Supply Chain",
		"support-app":                         "AWS Support App",
		"support":                             "AWS Support",
		"swf":                                 "Amazon Simple Workflow Service",
		"synthetics":                          "Synthetics",
		"taxsettings":                         "Tax Settings",
		"textract":                            "Amazon Textract",
		"timestream-influxdb":                 "Timestream InfluxDB",
		"timestream-query":                    "Amazon Timestream Query",
		"timestream-write":                    "Amazon Timestream Write",
		"tnb":                                 "AWS Telco Network Builder",
		"transcribe":                          "Amazon Transcribe Service",
		"transfer":                            "AWS Transfer Family",
		"translate":                           "Amazon Translate",
		"trustedadvisor":                      "TrustedAdvisor Public API",
		"verifiedpermissions":                 "Amazon Verified Permissions",
		"voice-id":                            "Amazon Voice ID",
		"vpc-lattice":                         "Amazon VPC Lattice",
		"waf-regional":                        "AWS WAF Regional",
		"waf":                                 "AWS WAF",
		"wafv2":                               "AWS WAFV2",
		"wellarchitected":                     "AWS Well-Architected Tool",
		"wisdom":                              "Amazon Connect Wisdom Service",
		"workdocs":                            "Amazon WorkDocs",
		"workmail":                            "Amazon WorkMail",
		"workmailmessageflow":                 "Amazon WorkMail Message Flow",
		"workspaces-instances":                "Amazon Workspaces Instances",
		"workspaces-thin-client":              "Amazon WorkSpaces Thin Client",
		"workspaces-web":                      "Amazon WorkSpaces Web",
		"workspaces":                          "Amazon WorkSpaces",
		"xray":                                "AWS X-Ray",
	}
}
